FROM container-registry.oracle.com/os/oraclelinux:9 AS builder

ARG version

RUN dnf config-manager --enable ol9_codeready_builder && \
    dnf -y install git make golang patch && \
    go version

# Copy the contents of the repository
COPY . /workspace/go/src/github.com/external-snapshotter

ENV GOPATH=/workspace/go CGO_ENABLED=0
WORKDIR /workspace/go/src/github.com/external-snapshotter

RUN patch < olm/builds/go-build.patch

RUN make build REV="$version"

FROM container-registry.oracle.com/os/oraclelinux:9-slim

# COPY LICENSE NOTICE THIRD_PARTY_LICENSES.txt olm/SECURITY.md /usr/share/licenses/
COPY --from=builder /workspace/go/src/github.com/external-snapshotter/LICENSE \
     /workspace/go/src/github.com/external-snapshotter/olm/SECURITY.md \
     /workspace/go/src/github.com/external-snapshotter/THIRD_PARTY_LICENSES.txt /usr/share/licenses/

RUN microdnf update -y && \
    microdnf clean all && \
    rm -rf /var/cache/yum/* && \
    test -d /LICENSES || ln -s /usr/share/licenses /LICENSES

WORKDIR /

COPY --from=builder /workspace/go/src/github.com/external-snapshotter/bin/csi-snapshotter /usr/bin

ENTRYPOINT ["/usr/bin/csi-snapshotter"]
