@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = "8.3.0";
String imgTag  = "v" + version;

imagePipeline(
    branchPattern: new BranchPattern(master: 'oracle/release/' + version, feature: '(?!^release/.*$)(^.*$)'),
    containers: [
            ('container-registry.oracle.com/olcne/csi-snapshotter:' + imgTag): 'olcne/csi-snapshotter:' + imgTag,
            ('container-registry.oracle.com/olcne/snapshot-controller:' + imgTag): 'olcne/snapshot-controller:' + imgTag
    ],
    platforms: ['ol9'],
    architectures: ['x86_64', 'aarch64'],
    golang: "1.23.7",
    buildScript: "sh olm/build-image.sh"
)

