@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = "{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}";
String imgTag  = "v" + version;

olcnePipeline(
    branchPattern: new BranchPattern(master: 'oracle/release/' + version, feature: 'feature/.*'),
    containers: [('container-registry.oracle.com/olcne/csi-snapshotter:' + imgTag): 'olcne/csi-snapshotter:' + imgTag],
    platforms: ['ol8'],
    architectures: ['x86_64', 'aarch64'],
)

